# Site settings
title: Jenson/Swenson/Straub 2015
email: ben@straub.cc
url: https://wi.github.io
description: "A site for the Jenson/Swenson/Straub reunion of 2015"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Ben Straub

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  # - title: twitter
  #   url: https://twitter.com/SBootstrap
  # - title: facebook
  #   url:
  # - title: stack-overflow
  #   url: http://stackoverflow.com/questions/tagged/jekyll
  # - title: bitbucket
  #   url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/ben/reunion

# Build settings
markdown: kramdown
permalink: pretty
